name: First job
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_KEY: ${{secrets.VERCEL_ORG_KEY}}
      VERCEL_PROJ_KEY: ${{secrets.VERCEL_PROJ_KEY}}
      VERCEL_TOKEN: ${{secrets.TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install packages
        run: yarn
      - name: build the project
        run: yarn build
      - name: deploy to vercel
        env:
          VERCEL_ORG_KEY: $VERCEL_ORG_KEY
          VERCEL_PROJ_KEY: $VERCEL_PROJ_KEY
        run: yarn deploy
      - name: setup finish
        run: echo "hurray"