name: First job
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install packages
        run: yarn
      - name: build the project
        run: yarn build
      - name: deploy to vercel
        env:
          VERCEL_ORG_KEY: sEBm10HX9ILVDJusLsktrjQy
          VERCEL_PROJ_KEY: prj_SRI6uAhg41sGuxbAGJ0EPEXhXqJQ
        run: yarn deploy
      - name: setup finish
        run: echo "hurray"